# !/usr/bin/python

import os, sys

# listing directories
print "The dir is: %s"%os.listdir(os.getcwd())

# renaming directory ''tutorialsdir"
os.rename("vsg-0.png","vsg.png")
os.rename("unk-0.png","unk.png")
os.rename("Ubx-0.png","Ubx.png")
os.rename("twin-0.png","twin.png")
os.rename("tsr-0.png","tsr.png")
os.rename("tmod-0.png","tmod.png")
os.rename("Top1-0.png","Top1.png")
os.rename("Tm1-0.png","Tm1.png")
os.rename("tkv-0.png","tkv.png")
os.rename("syt1-0.png","syt1.png")
os.rename("syb-0.png","syb.png")
os.rename("stwl-0.png","stwl.png")
os.rename("SmD3-0.png","SmD3.png")
os.rename("sm-0.png","sm.png")
os.rename("shot-0.png","shot.png")
os.rename("sgg-0.png","sgg.png")
os.rename("sema1b-0.png","sema1b.png")
os.rename("Sema-2a-0.png","Sema-2a.png")
os.rename("Rpl10Ab-0.png","Rpl10Ab.png")
os.rename("Rack1-0.png","Rack1.png")
os.rename("Rab11-0.png","Rab11.png")
os.rename("pum-0.png","pum.png")
os.rename("pop2-0.png","pop2.png")
os.rename("pbl-0.png","pbl.png")
os.rename("Pax-0.png","Pax.png")
os.rename("Pat1-0.png","Pat1.png")
os.rename("Nrx-IV-0.png","Nrx-IV.png")
os.rename("Notch-0.png","Notch.png")
os.rename("nonA-0.png","nonA.png")
os.rename("nmo-0.png","nmo.png")
os.rename("NetA-0.png","NetA.png")
os.rename("nej-0.png","nej.png")
os.rename("Myo10A-0.png","Myo10A.png")
os.rename("mts-0.png","mts.png")
os.rename("Mnt-0.png","Mnt.png")
os.rename("mip130-0.png","mip130.png")
os.rename("mbc-0.png","mbc.png")
os.rename("mask-0.png","mask.png")
os.rename("lola-0.png","lola.png")
os.rename("Lk6-0.png","Lk6.png")
os.rename("kst-0.png","kst.png")
os.rename("if-0.png","if.png")
os.rename("hth-0.png","hth.png")
os.rename("heph-0.png","heph.png")
os.rename("GS2-0.png","GS2.png")
os.rename("Gli-0.png","Gli.png")
os.rename("gish-0.png","gish.png")
os.rename("Gdi-0.png","Gdi.png")
os.rename("Gdh-0.png","Gdh.png")
os.rename("flw-0.png","flw.png")
os.rename("fax-0.png","fax.png")
os.rename("Fas3-0.png","Fas3.png")
os.rename("eIF1A-0.png","eIF1A.png")
os.rename("ed-0.png","ed.png")
os.rename("Dys-0.png","Dys.png")
os.rename("dally-0.png","dally.png")
os.rename("cup-0.png","cup.png")
os.rename("cip4-0.png","cip4.png")
os.rename("cher-0.png","cher.png")
os.rename("cam-0.png","cam.png")
os.rename("bun-0.png","bun.png")
os.rename("brp-0.png","brp.png")
os.rename("B4-0.png","B4.png")
os.rename("Arpc1-0.png","Arpc1.png")
os.rename("Arp3-0.png","Arp3.png")
os.rename("arm-0.png","arm.png")
os.rename("aop-0.png","aop.png")
os.rename("Amph-0.png","Amph.png")

print "Successfully renamed."

# listing directories after renaming "tutorialsdir"
print "the dir is: %s" %os.listdir(os.getcwd())\